"""prod description made mandatrory

Revision ID: 0621b6deee6e
Revises: 5d430a3b67a7
Create Date: 2026-09-10 09:46:13.973560

"""
from alembic import op
import sqlalchemy as sa


revision = '0621b6deee6e'
down_revision = '5d430a3b67a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lead_enquiry', 'product_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lead_enquiry', 'product_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
