"""create location and salesmen tables

Revision ID: 2a107b1af0d9
Revises: d3de59bc36ec
Create Date: 2026-09-06 10:49:03.562989

"""
from alembic import op
import sqlalchemy as sa


revision = '2a107b1af0d9'
down_revision = 'd3de59bc36ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('location_code', sa.String(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_index(op.f('ix_location_location_code'), 'location', ['location_code'], unique=True)
    op.create_index(op.f('ix_location_location_id'), 'location', ['location_id'], unique=False)
    op.create_table('salesman',
    sa.Column('salesman_id', sa.Integer(), nullable=False),
    sa.Column('salesman_code', sa.String(), nullable=False),
    sa.Column('salesman_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('salesman_id')
    )
    op.create_index(op.f('ix_salesman_salesman_code'), 'salesman', ['salesman_code'], unique=True)
    op.create_index(op.f('ix_salesman_salesman_id'), 'salesman', ['salesman_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salesman_salesman_id'), table_name='salesman')
    op.drop_index(op.f('ix_salesman_salesman_code'), table_name='salesman')
    op.drop_table('salesman')
    op.drop_index(op.f('ix_location_location_id'), table_name='location')
    op.drop_index(op.f('ix_location_location_code'), table_name='location')
    op.drop_table('location')
    # ### end Alembic commands ###
