"""create employee table

Revision ID: 5d430a3b67a7
Revises: 23caa383e8fb
Create Date: 2026-09-08 11:14:54.155661

"""
from alembic import op
import sqlalchemy as sa


revision = '5d430a3b67a7'
down_revision = '23caa383e8fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(), nullable=True),
    sa.Column('honorifics', sa.Enum('mr', 'mrs', 'ms', 'dr', 'prof', name='honorific_enum'), nullable=True),
    sa.Column('employee_name', sa.String(), nullable=False),
    sa.Column('employee_phone', sa.String(), nullable=True),
    sa.Column('employee_phone_personal', sa.String(), nullable=True),
    sa.Column('employee_email', sa.String(), nullable=True),
    sa.Column('employee_designation', sa.String(), nullable=True),
    sa.Column('employee_department', sa.String(), nullable=True),
    sa.Column('employee_location', sa.String(), nullable=True),
    sa.Column('employee_status', sa.Enum('active', 'inactive', 'on_leave', name='employee_status_enum'), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('employee_id'),
    sa.UniqueConstraint('employee_email')
    )
    op.create_index(op.f('ix_employee_employee_code'), 'employee', ['employee_code'], unique=True)
    op.create_index(op.f('ix_employee_employee_id'), 'employee', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_employee_id'), table_name='employee')
    op.drop_index(op.f('ix_employee_employee_code'), table_name='employee')
    op.drop_table('employee')
    # ### end Alembic commands ###
