"""create lead_enquiry table

Revision ID: a9c84bdd5395
Revises: 
Create Date: 2026-09-03 09:29:23.531492

"""
from alembic import op
import sqlalchemy as sa


revision = 'a9c84bdd5395'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_enquiry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('product_description', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('customer_phone', sa.String(), nullable=False),
    sa.Column('salesman_code', sa.String(), nullable=False),
    sa.Column('salesman_name', sa.String(), nullable=False),
    sa.Column('location_code', sa.String(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='priority_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_enquiry_id'), 'lead_enquiry', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_enquiry_id'), table_name='lead_enquiry')
    op.drop_table('lead_enquiry')
    # ### end Alembic commands ###
