"""make product_description optional

Revision ID: d3de59bc36ec
Revises: a9c84bdd5395
Create Date: 2026-09-03 10:44:26.829334

"""
from alembic import op
import sqlalchemy as sa


revision = 'd3de59bc36ec'
down_revision = 'a9c84bdd5395'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lead_enquiry', 'product_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lead_enquiry', 'product_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
